version: '3.2'

networks:
  lan:

services:
    # nginx:
    #     image: nginx:stable-alpine
    #     container_name: nginx
    #     ports:
    #         - "8080:80"
    #     volumes:
    #         - ./backend:/var/www/html
    #         - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #     networks:
    #         - lan
    # php:
    #     build:
    #         context: .
    #         dockerfile: ./dockerfiles/php
    #     container_name: php
    #     volumes:
    #         - ./backend:/var/www/html
    #     networks:
    #         - lan
    #     ports:
    #         - "9000:9000"
    mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      container_name: mysql
      tty: true
      ports:
        - "4306:3306"
      environment:
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/logs:/var/log/mysql
        - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      networks:
        - lan